credentials:
  sashi:
    free_api_key: 
    free_secret_key: 
    api_key: 
    secret_key: 
    username : 
    password : 
    authenticator_token : 
  madhu:
    api_key: 
    secret_key: 
    username: 
    password: 
    authenticator_token: 
  sakhi:
    api_key: 
    secret_key: 
    username: 
    password: 
    authenticator_token:
